platform :ios, '9.0'

use_frameworks!

workspace 'iddog'

target 'Application' do
  project 'Application/Application.xcodeproj/'
  
  pod 'SwiftGen', '~> 6.0'

  target 'ApplicationTests' do
    inherit! :search_paths
  end
end
