platform :ios, '9.0'

use_frameworks!

workspace 'iddog'

pod 'SwiftGen', '~> 6.0'

target 'Application' do
  project 'Application/Application.xcodeproj/'
  
  pod 'Alamofire', '~> 4.9'

  target 'ApplicationTests' do
    inherit! :search_paths
  end
end

target 'Networking' do
  project 'Networking/Networking.xcodeproj/'
  pod 'Alamofire', '~> 4.9'
end
